#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) 2012-2021 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See docs/COPYRIGHT.rdoc for more details.
#++

# DO NOT MODIFY THIS FILE !!!
# Settings can be defined through the application in Admin -> Settings

repositories_automatic_managed_vendor:
  default: ''
project_gantt_query:
  default: ''
# encodings used to convert repository files content to UTF-8
# multiple values accepted, comma separated
repositories_encodings:
  default: ''
# encoding used to convert commit logs to UTF-8
commit_logs_encoding:
  default: 'UTF-8'
emails_footer:
  serialized: true
  default:
    en: |-
      You have received this notification because you have either subscribed to it, or are involved in it.
      To change your notification preferences, please click here: http://hostname/my/account
start_of_week:
  default: ''
first_week_of_year:
  default: ''
emails_header:
  serialized: true
  default:
    en: ''
