#-- copyright
# OpenProject is an open source project management software.
# Copyright (C) 2012-2021 the OpenProject GmbH
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License version 3.
#
# OpenProject is a fork of ChiliProject, which is a fork of Redmine. The copyright follows:
# Copyright (C) 2006-2013 Jean-Philippe Lang
# Copyright (C) 2010-2013 the ChiliProject Team
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
# See docs/COPYRIGHT.rdoc for more details.
#++

# DO NOT MODIFY THIS FILE !!!
# Settings can be defined through the application in Admin -> Settings

wiki_compression:
  default: ""
email_login: # use email address as login, hide login in registration form
  default: 0
host_name:
  default: localhost:3000
protocol:
  default: http
feeds_enabled:
  default: 1
feeds_limit:
  format: int
  default: 15
# Maximum size of files that can be displayed
# inline through the file viewer (in KB)
file_max_size_displayed:
  format: int
  default: 512
sys_api_enabled:
  default: 0
sys_api_key:
  default: ''
repository_authentication_caching_enabled:
  default: 1
repositories_automatic_managed_vendor:
  default: ''
user_format:
  default: :firstname_lastname
  format: symbol
cross_project_work_package_relations:
  default: 1
  format: boolean
notified_events:
  serialized: true
  default:
  - work_package_added
  - work_package_updated
  - work_package_note_added
  - status_updated
  - work_package_priority_updated
  - news_added
  - news_comment_added
  - file_added
  - message_posted
  - wiki_content_added
  - wiki_content_updated
  - membership_added
  - membership_updated
mail_handler_body_delimiters:
  default: ''
mail_handler_ignore_filenames:
  default: 'signature.asc'
mail_handler_body_delimiter_regex:
  default: ''
mail_suffix_separators:
  default: '+'
work_package_list_default_columns:
  serialized: true
  default:
  - id
  - subject
  - type
  - status
  - assigned_to
  - priority
work_package_list_default_highlighting_mode:
  default: 'inline'
work_package_list_default_highlighted_attributes:
  serialized: true
  default: []
display_subprojects_work_packages:
  default: 1
work_package_done_ratio:
  default: 'field'
default_projects_public:
  default: 0
default_projects_modules:
  serialized: true
  default:
  - calendar
  - board_view
  - work_package_tracking
  - news
  - costs
  - wiki
enabled_projects_columns:
  serialized: true
  default:
    - project_status
    - public
    - created_at
    - latest_activity_at
    - required_disk_space
project_gantt_query:
  default: ''
# Role given to a non-admin user who creates a project
new_project_user_role_id:
  format: int
  default: ''
# encodings used to convert repository files content to UTF-8
# multiple values accepted, comma separated
repositories_encodings:
  default: ''
# encoding used to convert commit logs to UTF-8
commit_logs_encoding:
  default: 'UTF-8'
repository_log_display_limit:
  format: int
  default: 100
emails_footer:
  serialized: true
  default:
    en: |-
      You have received this notification because you have either subscribed to it, or are involved in it.
      To change your notification preferences, please click here: http://hostname/my/account
start_of_week:
  default: ''
first_week_of_year:
  default: ''
rest_api_enabled:
  default: 1
session_ttl_enabled:
  default: 0
session_ttl:
  format: int
  default: 120
default_notification_option:
  default: 'only_my_events'
emails_header:
  serialized: true
  default:
    en: ''
work_package_startdate_is_adddate:
  default: 0
  format: boolean
user_default_timezone:
  default: ""
users_deletable_by_admins:
  default: 0
users_deletable_by_self:
  default: 0
invitation_expiration_days:
  default: 7
  format: int
journal_aggregation_time_minutes:
  default: 5
  format: int
registration_footer:
  serialized: true
  default:
    en:
repository_storage_cache_minutes:
  default: 720
  format: int
repository_truncate_at:
  default: 500
  format: int
repository_checkout_data:
  serialized: true
  default:
    git:
      enabled: 0
    subversion:
      enabled: 0
demo_projects_available:
  default: false
boards_demo_data_available:
  default: false
security_badge_displayed:
  default: true
oauth_allow_remapping_of_existing_users:
  default: false
  format: boolean
apiv3_cors_enabled:
  default: false
  format: boolean
apiv3_cors_origins:
  serialized: true
  default: []
